kind: pipeline
name: default

steps:

  - name: compile
    image: node
    commands:
      - npm install
      - ./node_modules/typescript/bin/tsc

  - name: aws-cdk
    image: eignhpants/docker-aws-cdk
    commands:
    - cdk synth
